### ISSUE TITLE
Raspberry PI4 : Raspian - ALSA-RAVENNA-AES67-Driver

### ISSUE THREAD

**Issue by yboujraf** [dewiweb/ALSA-RAVENNA-AES67-Driver#1]
Dear @dewiweb 

Do you think I could use the ALSA Ravenna AES67 on a RASPBERRY PI 4?

Finally, is there a way to reach in Private Message ?

Best Regards,
Youssef

**Comment by dewiweb** [comment]
Hello @yboujraf ,
I'm not the developer of  ALSA Ravenna AES67. I only port the original bitbucket repository   ( https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm ) to github for more visibility.
I think  it could be possible to implement it on rpi but maybe you could have more information from Merging Technologies...

You could still contact me  dewiweb@gmail.com for other informations.
Best regards,
Dewiweb
