### ISSUE TITLE
Build error on Ubuntu Server 22.04 Kernel 5.15

### ISSUE THREAD

**Issue by elguapo71** [dewiweb/ALSA-RAVENNA-AES67-Driver#2]
I got this error message when build this kernel:
`error: implicit declaration of function ‘__put_user_x’; did you mean ‘__put_user_8’? [-Werror=implicit-function-declaration]`
How to fix it?

**Comment by dewiweb** [comment]
This repo is an clone forked 3 years ago from:
[https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/src/master/](https://bitbucket.org/MergingTechnologies/ravenna-alsa-lkm/src/master/)
There's some update on the original repo, so I encourage you to follow the link :-)
